services:
  - docker:19.03.7-dind
stages:
  - package
  - docker_build
mvn_build_job:
  only:
    - main
  image: maven:3.6.3-jdk-8-slim
  stage: package
  script:
    - mvn clean install && mvn package
  artifacts:
    paths:
      - industryCloud/target/*.jar
docker_build_job:
  only:
    - main
  image: docker:stable
  stage: docker_build
  script:
    - docker build -t registry.cn-shanghai.aliyuncs.com/ym_library/industry-cloud:1.0 .
    - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD registry.cn-shanghai.aliyuncs.com
    - docker push registry.cn-shanghai.aliyuncs.com/ym_library/industry-cloud:1.0