spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:10.2.13.141}:3306/ic?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${MYSQL_USER:jh_dev}
    password: ${MYSQL_PWD:7F0OSTuFuCzEGWp0lgsGWN}
  jpa:
    show-sql: true
    generate-ddl: true
    database: mysql