erupt-app:
  # 是否开启水印，1.12.0 及以上版本支持
  water-mark: true
  # 登录失败几次出现验证码，值为0时表示一直需要登录验证码
  verify-code-count: 2
  # 登录密码是否加密传输，特殊场景如：LDAP登录可关闭该功能获取密码明文
  pwd-transfer-encrypt: true
  # 是否开启密码重置功能，关闭后前端会屏蔽所有重置密码的入口适用于 ldap 等场景，1.12.7 及以上版本支持
  reset-pwd: true
  # 多语言配置
  locales: [
    "zh-CN",      # 简体中文
    "zh-TW",      # 繁体中文
    "en-US",      # English
    "fr-FR",      # En français
    "ja-JP",      # 日本語
    "ko-KR",      # 한국어
    "ru-RU",      # русск
    "es-ES"       # español
  ]
  # 自定义登录页路径，1.10.6 及以上版本支持，支持http网络路径
  # login-page-path: /customer-login.html
erupt:
  # 是否开启csrf防御
  csrf-inspect: true
  # 开启redis方式存储session，默认false，开启后需在配置文件中添加redis配置（同 Spring Boot）
  redis-session: false
  # redis session是否自动续期，1.10.8及以上版本支持
  redis-session-refresh: false
  # 附件上传存储路径, 默认路径为：/opt/erupt-attachment
  upload-path: D:/erupt/pictures
  # 是否保留上传文件原始名称
  keep-upload-file-name: false
  # 项目初始化方式，NONE 不执行初始化代码、EVERY 每次启动都进行初始化、FILE 通过标识文件判断是否需要初始化
  init-method-enum: file
  # 默认语言，1.12.3及以上版本支持
  default-locales: zh-CN
  upms:
    # 登录session时长（redisSession为true时有效）
    expire-time-by-login: 60
    # 严格的角色菜单策略，如果非管理员用户拥有“角色管理权限”则仅能编辑已有权限的角色菜单
    strict-role-menu-legal: true
    # 是否开启任务调度（导入erupt-job时有效）
    # job.enable: true
    # 是否记录操作日志，默认true，该功能开启后可在【系统管理 → 操作日志】中查看操作日志
    # security.record-operate-log: true
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:192.168.123.222}:3306/ic?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PWD:snnuiabc}
    #url: jdbc:mysql://${MYSQL_HOST:gateway01.ap-northeast-1.prod.aws.tidbcloud.com}:4000/ic?sslMode=VERIFY_IDENTITY&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    #username: ${MYSQL_USER:2Pni9jNeHoQ8reh.root}
    #password: ${MYSQL_PWD:vyQSx94I6o6xAO4x}
  jpa:
    show-sql: true
    generate-ddl: true
    database: mysql
  redis:
    database: 0
    timeout: 10000
    host: ${REDIS_HOST:192.168.123.222}
wx:
  mp:
    appid: "wx1cc0fe15e760d844"
    secret: "a3f018a5117a92a06bd175957ddb191f"
    token: "abcdefg1234567890"
    aesKey: "qp17qGwMPTLNSqqfFqeYN1MrDt5MEB3kgOkp5hhQRcM"
    certification: ${WX_CERTIFICATION:false}
oapi:
  api-secret-key: 8164c9cf32282681c691d1c766f47c97.DspJVDBivno5cRgJ

openai:
  api-secret-key: sk-pNjKFFGWHdNJQdZq5d617bFaF7094a43A82a229b8511EeAc
  base-url: https://api.qingzaoyun.com/
  timeout: 30
